#!/usr/bin/env python3

import os
import sys
import argparse
from multiprocessing import cpu_count
from esppy.pid import Pid
from esppy.supervisor import Supervisor


def _spawn(module_name, function_name, *args, **kwargs):
    return Pid(module_name, function_name, args, kwargs)


__builtins__.spawn = _spawn


parser = argparse.ArgumentParser()
parser.add_argument('file')
parser.add_argument('--master', action='store_true', default=True)
parser.add_argument('--slave', action='store_true', default=False)
parser.add_argument('-w', '--workers', default=cpu_count(), type=int)
args = parser.parse_args()
print(args)

cwd = os.getcwd()
added_path = os.path.abspath(os.path.join(cwd, os.path.dirname(args.file)))
sys.path = [added_path] + sys.path

supervisor = Supervisor(args)
supervisor.run()
